### ISSUE TITLE
Missing depends

### ISSUE THREAD

**Issue by bvaudour** [KaOS-Community-Packages/bitwarden-cli#1]
According to the [README](https://github.com/bitwarden/cli#bitwarden-command-line-interface) bitwarden is written in Node.js. So it should depend of nodejs instead of gcc-libs.

**Comment by panbroggi** [comment]
I had some research on it before keeping the dependency (I have noticed it the AUR version).
On the bitwarden/cli README this package corresponds to the native executable, which is reported to have no dependency at all. However, there is an [issue](https://github.com/bitwarden/cli/issues/155) reporting that it does not work on `musl libc`and this is why I kept it. Should I remove it?

**Comment by bvaudour** [comment]
No you’re right. Sorry, I should have read all the README.

Closing the issue.
